name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ou a versão que você usa

      - name: Instalar dependências
        run: npm ci

      - name: Instalar browsers do Playwright
        run: npx playwright install

      - name: Rodar testes Playwright
        run: npx playwright test
